### PR TITLE
fixes #115: @@toStringTag is writable now

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #115. Option 2: just make `@@toStringTag` writable.

### CODE REVIEW

**Comment by michaelficarra** [comment]
While I appreciate the thumbs-ups, I actually need an approving review here to merge.

Feedback from committee was to make this property writable.

**Review by bakkot — APPROVED** [review]
LGTM but might be worth having an explicit emu-note calling out the unusual value and the reason for it; it's not obvious that this boilerplate is different from all the other boilerplate.

**Comment by michaelficarra** [comment]
I've updated the PR to just remove the description of the property descriptor properties since

> Every other [data property](https://tc39.es/ecma262/#sec-object-type) described in clauses [19](https://tc39.es/ecma262/#sec-global-object) through [28](https://tc39.es/ecma262/#sec-reflection) and in Annex [B.2](https://tc39.es/ecma262/#sec-additional-built-in-properties) has the attributes { [[Writable]]: true, [[Enumerable]]: false, [[Configurable]]: true } unless otherwise specified.

and these `@@toStringTag` properties now use the default.

**Comment by michaelficarra** [comment]
Per @bakkot's request, I've added a note anyway.

**Review by bakkot — APPROVED** [review]

**Pull request merged**
