### PR TITLE
Add a note about `core-js` polyfilling

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by devsnek** [comment]
having a link is fine, i'd hesitate to put actual documentation for the polyfill here though.

**Comment by zloirock** [comment]
Makes sense. Just tried to do the note more useful -)

**Comment by michaelficarra** [comment]
@zloirock Does the core-js implementation match the current spec text?

**Comment by zloirock** [comment]
@michaelficarra yep.

**Comment by zloirock** [comment]
ping @devsnek

**Pull request merged**
