### PR TITLE
Add itiriri and JS linq to Prior Art

### PR DESCRIPTION
**Pull request by xmedeko**

### CODE REVIEW

**Comment by slikts** [comment]
Including libraries without a notability criteria would make the list overly long.

**Comment by devsnek** [comment]
I'm about to delete the table anyway

**Comment by xmedeko** [comment]
@devsnek I do not know what's the habit in TC39 documents, but I like the Prior Art section since it gives link and credit to a community effort to tackle the same problem and makes it simple to click to get an inspiration from elsewhere.
I understand you do not want to mention any tiny project and maybe not want to have a hassle arguing which project to add and which not. But still think the Prior Art is nice even if my PR is rejected 😉

**Comment by ljharb** [comment]
@devsnek the prior art section should remain forever; it's an important part of archival history of every proposal.

**Pull request closed without merging**
