### PR TITLE
fix React usage in README

### PR DESCRIPTION
**Pull request by trotyl**

### CODE REVIEW

**Comment by devsnek** [comment]
thank you :)

**Comment by devsnek** [comment]
@bakkot a lot of other proposals have used common ui libraries in motivational examples, i don't think its a huge problem. <sub>and we could always say its e4x :)</sub>

**Comment by bakkot** [comment]
UI libraries are fine, since they're still JS; syntax extensions are not.

**Comment by domenic** [comment]
I agree it's best to stick to standard syntax, if nothing else to avoid confusing committee members. I know I myself have many times found proposals that use TypeScript in their readmes very confusing.

I'd suggest using a tagged template variant of the same example, e.g. using the htm library.

**Comment by ljharb** [comment]
could also use React.createElement

**Pull request merged**
